### ISSUE TITLE
Send email of impending due date

### ISSUE THREAD

**Issue by creecros** [creecros/SendEmailCreator#1]
Reminder for myself: I need to look at this again, not working currently, at least not for myself.

**Comment by AlgyTaylor** [comment]
How strange .. I was just going to add an issue to say it'd be really handy to be able to send an email when a due date had been / was about to be reached!

:+1:

**Comment by creecros** [comment]
time() seems to be the culprit
tried strtotime("now") also get nothing. I'm at a loss.

**Comment by creecros** [comment]
problem solved, action works, tested and true.

**Comment by AlgyTaylor** [comment]
It doesn't seem to be working on my current install ...

**Comment by creecros** [comment]
How are you installing?

**Comment by creecros** [comment]
And, any logs?

Works on my install, latest version. Should work on most versions.

**Comment by creecros** [comment]
Everyday at 7pm...
![image](https://user-images.githubusercontent.com/26339368/33959381-46fa3eb0-e015-11e7-8007-f97fd342ad37.png)

**Comment by AlgyTaylor** [comment]
Thanks - that's sorted it :)
