### ISSUE TITLE
Send email when commented on task

### ISSUE THREAD

**Issue by AlgyTaylor** [creecros/SendEmailCreator#11]
Hi there,

Thanks for sendemailcreator - we've been using it since at the early days, it's so useful :)

One request I've had is, would it be possible to add the ability to send an email to (person) when someone adds a comment?

Thanks,
Algy

**Comment by creecros** [comment]
That doesn't already exist? If not, yes, should be easy. Have a long to do list, so stay tuned.

**Comment by creecros** [comment]
https://github.com/creecros/SendEmailCreator/releases/tag/1.2.0
