### ISSUE TITLE
notification:overdue-tasks vs trigger:tasks

### ISSUE THREAD

**Issue by TimoStahl** [creecros/SendEmailCreator#12]
Hey @creecros,

in our system we have the following jobs:

trigger:tasks -> every hour
notification:overdue-tasks -> once a day at 6:00

We like the idea to inform the user **before** the due date is overdue, like this plugin does.
Unfortunately the trigger of this plugins runs every hour :(

Maybe it is possible to trigger this action by notification:overdue-tasks as well and not by the task backgound worker?

Regards,
Timo

**Comment by creecros** [comment]
Your running cron every hour?

**Comment by creecros** [comment]
A while back, I added a rule for the task due date action, it will only mail once per day. I never added it to the subtask due date action though.

**Comment by BlueTeck** [comment]
`./cli cronjob` once at 06:00 to collect data and send overdue notifications
`./cli trigger:tasks` every hour to trigger some actions more than once a day

This rule for subtask would be perfect :)

**Comment by creecros** [comment]
I'll have to find a solution for subtasks, i knew there was a reason why I didn't add to being with:
https://github.com/kanboard/kanboard/issues/4066#issuecomment-436100088

**Comment by creecros** [comment]
https://github.com/creecros/SendEmailCreator/commit/ea3cd7f369623666909e39fe7f17bd302e873604
