### ISSUE TITLE
Error :  PHP Warning

### ISSUE THREAD

**Issue by kwetnico** [creecros/SendEmailCreator#18]
Hello,

I user SendEmailCreator's plugin with the last version to Kanboard, but i have this error (file : /tmp/kanboard-cli.log) : 
"
PHP Warning:  A non-numeric value encountered in /var/www/html/kanboard/plugins/SendEmailCreator/Action/TaskEmailDue.php on line 110
"

My Crontab : 
00 07 * * 1-5 cd /var/www/html/kanboard && ./cli cronjob >>/tmp/kanboard-cli.log 2>&0

Thanks

**Comment by creecros** [comment]
and to be clear, is `$verbose` set to true or false?

https://github.com/creecros/SendEmailCreator/blob/345c98f4077755826ed74825deffb23a7ccb825e/Action/TaskEmailDue.php#L108

**Comment by kwetnico** [comment]
> and to be clear, is `$verbose` set to true or false?
> 
> https://github.com/creecros/SendEmailCreator/blob/345c98f4077755826ed74825deffb23a7ccb825e/Action/TaskEmailDue.php#L108

I don't have this  option line 108 but i see my version is 1.2.1.
Go to update the plugin..

**Comment by kwetnico** [comment]
> and to be clear, is `$verbose` set to true or false?
> 
> https://github.com/creecros/SendEmailCreator/blob/345c98f4077755826ed74825deffb23a7ccb825e/Action/TaskEmailDue.php#L108

With the last version to plugin : 

"PHP Warning:  A non-numeric value encountered in /var/www/html/kanboard/plugins/SendEmailCreator/Action/TaskEmailDue.php on line 120"

$verbose set to false

**Comment by creecros** [comment]
well, that changes things. duration is the only parameter on line 120. It must be a number. what is your duration set to? did you leave it empty?

**Comment by kwetnico** [comment]
> well, that changes things. duration is the only parameter on line 120. It must be a number. what is your duration set to? did you leave it empty?

line 120 : 
"
    $max_duration = $this->getParam('duration') * 86400;
"

**Comment by creecros** [comment]
yes, I know the code,, your missing the point. when you set up your action, what did YOU set the duration to? did you leave the field blank?

**Comment by kwetnico** [comment]
> yes, I know the code,, your missing the point. when you set up your action, what did YOU set the duration to? did you leave the field blank?

Where change the duration ?

**Comment by creecros** [comment]
![image](https://user-images.githubusercontent.com/26339368/109166950-404d6a80-774b-11eb-8b1e-0d45e1515172.png)

![image](https://user-images.githubusercontent.com/26339368/109166921-39bef300-774b-11eb-94a2-8838c68eab30.png)

**Comment by kwetnico** [comment]
> ![image](https://user-images.githubusercontent.com/26339368/109166950-404d6a80-774b-11eb-8b1e-0d45e1515172.png)
> 
> ![image](https://user-images.githubusercontent.com/26339368/109166921-39bef300-774b-11eb-94a2-8838c68eab30.png)
> 
> It cannot be blank, like above

yes my configuration : 
Nom de l'évènement = Tâche planifiée quotidienne pour les tâches
Sujet de l'email = Taches en retard
Durée en jours = **1**
Send_to = assignee

Send email notification of impending due date
--
Nom de l'évènement = Tâche planifiée quotidienne pour les tâchesSujet de l'email = Taches en retardDurée en jours = 1Send_to = assignee



Send email notification of impending due date
--
Nom de l'évènement = Tâche planifiée quotidienne pour les tâchesSujet de l'email = Taches en retardDurée en jours = 1Send_to = assignee

**Comment by kwetnico** [comment]
![2021-02-25_152941](https://user-images.githubusercontent.com/55591810/109167770-650f0580-777e-11eb-97f2-abe0b2fa086a.jpg)

**Comment by creecros** [comment]
try now, and if that doesn't fix it, i have 1 more idea

**Comment by kwetnico** [comment]
> try now, and if that doesn't fix it, i have 1 more idea

Yes ! it's good !! ;)

**Comment by creecros** [comment]
cool. FYI, that means there is an action somewhere with a missing value for `duration`, might want to check all your projects. I have it set to default to `0` if thats the case.
