### ISSUE TITLE
TaskEmailDue fails with error when trying to send mails to "creator"

### ISSUE THREAD

**Issue by imfx77** [creecros/SendEmailCreator#25]
https://github.com/creecros/SendEmailCreator/blob/56feadc98138613cac04948fb243dfb4c90e613b/Action/TaskEmailDue.php#L174

the variable $project is not initialized in the second cycle for the creator
hence error upon trying to index null object

**Comment by creecros** [comment]
Good catch, I see it.

Can you make a PR, or do you need me to do it?

**Comment by creecros** [comment]
remdae the release to accomadate
