### ISSUE TITLE
Warning: Undefined array key "due_date"

### ISSUE THREAD

**Issue by GusevVictor** [creecros/SendEmailCreator#26]
I installed:

    Application version: v1.2.32
    PHP version: 8.2.8
    PHP SAPI: fpm-fcgi
    Auto Email Extended Actions 1.2.5
    SubtaskDueDate 1.1.3

If I add Automatic action for the project:

    Send email notification of impending subtask due date

Event name = Daily background job for tasks
Duration in days = 1
Choose a column to ignore, when a task is in this column, no emails will be sent. = Backlog

The job returns an error meaasge. The message is

    Warning: Undefined array key "due_date" in /var/www/app/plugins/SendEmailCreator/Action/SubTaskEmailDue.php on line 78

After that there is no any work email notify at all.

Can you fix that please?

**Comment by imfx77** [comment]
I guess you took note of this comment from the plugin README?
```
4.) Send email of an impending subtask due date to assigned user
   This requires the [Subtask Due Date Plugin](https://github.com/eSkiSo/Subtaskdate) to function.
```
SUBtasks normally don't have "due_date" field, and the above plugin is that adds it.

**Comment by creecros** [comment]
He claims he installed it.

I haven't had time to do any tests, but I would suggest insuring that both plugins do infact exist, and both are working. It's possible you need to restart your server, or the Subtask due date plugin failed to update your database schema. Just some things you can check. 

I'm pretty sure once I get a chance to run tests on the latest KB version, there most likely won't be anything wrong with the code, but we'll see.

**Comment by GusevVictor** [comment]
Dear @creecros , I removed:

1. Send email notification of impending subtask due date from my project
2. Auto Email Extended Actions plugin
3. SubtaskDueDate plugin

I restarted docker service:
```
vgusev@vgusev:/srv/kanboard$ docker compose restart
[+] Restarting 2/2
 ✔ Container kanboard-db-1        Started                                                                                                  0.9s 
 ✔ Container kanboard-kanboard-1  Started  
```
I setup:

1. SubtaskDueDate plugin

Then restart docker.

Then I have setup:

1. Auto Email Extended Actions plugin

Then restart docker.

After that I added "Send email notification of impending subtask due date" to my project again.
Then restart docker.

The cron job says twice:
```
Warning: Undefined array key "due_date" in /var/www/app/plugins/SendEmailCreator/Action/SubTaskEmailDue.php on line 78

Warning: Undefined array key "due_date" in /var/www/app/plugins/SendEmailCreator/Action/SubTaskEmailDue.php on line 78
```

Please help. I'm very like your plugins.

Best regards!

**Comment by creecros** [comment]
i see the issue. I'll send an update in a moment.

**Comment by creecros** [comment]
try it now
