### ISSUE TITLE
Send e-mail on changing task

### ISSUE THREAD

**Issue by Claytondiver** [creecros/SendEmailCreator#7]
Hi @creecros, is there a way to make this plugin works for "saving task" event? 
I would like to automatic send e-mail to assignee when the task is changed, for instance, when I change the assignee. It would also be great for cases where the task is created with no assignee and then, later, it is assigned to someone.
Is that possible?

**Comment by Claytondiver** [comment]
I´m sorry, but I don´t know how to do it.... How do I do that?
Thanks again!

**Comment by creecros** [comment]
updated with release [0.0.4](https://github.com/creecros/SendEmailCreator/tree/0.0.4)

**Comment by Claytondiver** [comment]
So we updated to 0.0.4. 
It works only if I change something other than just the assignee. If the only change is the assignee, I don´t get the e-mail...

**Comment by creecros** [comment]
Ok, just noticed there is a separate event for assignee change, EVENT_ASSIGNEE_CHANGE

**Comment by creecros** [comment]
new release: https://github.com/creecros/SendEmailCreator/releases/download/0.0.5/SendEmailCreator-0.0.5.zip
